### ISSUE TITLE
TODO: enable travis builds and seamless non-go builds

### ISSUE THREAD

**Issue by jwkohnen** [pboyer/antlr4#13]
See #9 and #12.

**Comment by pboyer** [comment]
I hit the switch on Travis.

**Comment by jwkohnen** [comment]
Nice, it should fail, but it is nice to have it in writing. :D

**Comment by pboyer** [comment]
:D

**Comment by pboyer** [comment]
Closing this as I believe we've got what we need for now...

**Comment by jwkohnen** [comment]
I think we can do better. Maybe I have an idea and I could fold this issue together with some patch that enables the `-package` command line option of the ANTLR tool. For now... ya I agree. :)
