### ISSUE TITLE
Gitter?

### ISSUE THREAD

**Issue by willfaught** [pboyer/antlr4#24]
Any interest in setting up Gitter for pboyer/antlr4? I've never used it before, but it seems less clunky than filing issues when I want to ask dumb questions...

(@pboyer, @wjkohnen)

**Comment by jwkohnen** [comment]
Setting up and using gitter is very easy. @pboyer should do it, that makes referencing tickets easier. The web app is a performance hog, but they offer XMPP and IRC connectors in case that is too annoying. 

https://gitter.im/

**Comment by pboyer** [comment]
Tada! https://gitter.im/pboyer/antlr4
