### ISSUE TITLE
TestParseTrees is ok

### ISSUE THREAD

**Issue by sridharxp** [pboyer/antlr4#47]
Java Array to String works differently from Go Array to String (in fmt.Println).
So TestTokenAndRuleContextString is not a failure
Go creates [a b c] whereas java [a, b, c] Change the assert to

```
assertEquals(_
            "[a s]\n" +
            "(a x)\n", _found);



```

**Comment by pboyer** [comment]
@sridharxp This should be fixed. Thanks for the help. Let me know if you have any other test fixes. I'm happy to accept PR's to this fork, of course.
