### ISSUE TITLE
Typo in prediction_context.go

### ISSUE THREAD

**Issue by sridharxp** [pboyer/antlr4#60]
File: prediction_context.go
Line: 386
error: 
`bc, ok2 := a.(*BaseSingletonPredictionContext)`
correct:
`bc, ok2 := b.(*BaseSingletonPredictionContext)`
One test less to go; I think it is 
`testAmbiguityNoLoop`

**Comment by pboyer** [comment]
Nice! Thanks @sridharxp. I'll take a look.
