### ISSUE TITLE
s/var bla =/bla :=

### ISSUE THREAD

**Issue by pboyer** [pboyer/antlr4#65]

**Comment by willfaught** [comment]
?

I use var where I can to match const, func, and type declaration syntax, but I know := is common too.

**Comment by pboyer** [comment]
If there's a right hand side at the declaration site, `:=` is idiomatic and makes code more robust to refactoring. I only use `var` for places where control flow leads to different assignments or in the package block where `:=` is not allowed.

**Comment by willfaught** [comment]
I would argue that it's less robust to refactoring because of unintentional
variable shadowing, but you're right that it's commonly done and not wrong.

**Comment by pboyer** [comment]
Isn't variable shadowing an issue regardless of declaration syntax? e.g.

``` go
    var foo = 1;
    {
        var foo = "string";
        fmt.Println(foo);
    }
    fmt.Println(foo)
```

is the same as:

``` go
    foo := 1;
    {
        foo := "string";
        fmt.Println(foo);
    }
    fmt.Println(foo)
```

But maybe you have some other case in mind?

**Comment by pboyer** [comment]
By the way, my main reason for saying `:=` is more robust to refactoring is it avoids the (usually) redundant `var foo Type = ...`. I really should have mentioned that. This kind of statement _does_ have a semantic difference viz; the type of `Foo` might be an interface type allowing more general assignment.

**Comment by pboyer** [comment]
Closing this, but shop talk is still allowed. ;)

**Comment by willfaught** [comment]
You're right, the := syntax functions the same in the nested block case.
Didn't think that one through.

If you paste into the same block, it could be problematic. Parallel
assignment meaning could change from (for example) two declarations to one
declaration and one assignment (common with reused err vars), or vice
versa. The meaning of the statement is based on its context, and that's
ripe for copy/paste errors, whereas var decls are unambiguous. If you only
use := where necessary (like with parallel assignment with reused err
vars), it signals to the reader that you're doing something clever. It's
more robust, in my view.
