### ISSUE TITLE
Tool src modification

### ISSUE THREAD

**Issue by sridharxp** [pboyer/antlr4#71]
Files in tool/src... are modified for golang port.
In files `LeftRecursiveRuleFunction, RuleActionFunction, RuleFunction, RuleSempredFunction, CodeGenerator` variables are added for use. In `Recognizer.java` code is modified to export lists with the possibility of clashing with other ports. Why not modify Go.stg to use arrays?  Added`contextSuperClass`variage from 5.4.3 to the template also.
[Go.txt](https://github.com/pboyer/antlr4/files/526302/Go.txt)
[Recognizer.txt](https://github.com/pboyer/antlr4/files/526304/Recognizer.txt)

**Comment by pboyer** [comment]
I'll take a look later. It appears all tests pass on all language targets today.

**Comment by sridharxp** [comment]
Great Awesome
Ran Tests. **No Failures; No Errors.**

**Comment by sridharxp** [comment]
Looking at implementation of `contextSuperClass` ..... `contextSuperClass` is custom implementation of `BaseParserRuleContext`, not an extension  of `ParserRuleContext` interface. Is my understanding Correct?

**Comment by pboyer** [comment]
Yup.

**Comment by sridharxp** [comment]
Updating `Go.stg` with latest changes...
[GostgUpdate.txt](https://github.com/pboyer/antlr4/files/531819/GostgUpdate.txt)
.

**Comment by pboyer** [comment]
@sridharxp I'm not sure what the above change is for.

**Comment by sridharxp** [comment]
Files in tool/src/.../*.java are common to all implementation. Some files mentioned above are modified to add a variable`recognizerName` support go method declarations. That is necessary as far my understanding goes. When merging upstream they may be integrated easily as opposed to code that modifies existing variable's type. So this `Go.stg` that accepts arrays from `Recognizer.java`. Excuse me if my understanding of target  development and integration is wrong.

**Comment by pboyer** [comment]
@willfaught Can you give this some thought? It seems related to the `recognizerName` changes you made.

**Comment by willfaught** [comment]
I'm sorry, I'm not following what's being discussed here. What's the question?

**Comment by sridharxp** [comment]
Looks like with the upstream merge, ie with suitable modifications in Go.stg there is no need for go target specific code in common tool/src... and so are removed. The points raised are all solved.

**Comment by parrt** [comment]
I'll close then :)
