### ISSUE TITLE
_x redeclared in this block

### ISSUE THREAD

**Issue by millergarym** [pboyer/antlr4#88]
First of all Peter, thanks this is looking good.

I've found a case where generated code produces a compile.
The var _x is redeclared when assigning a rule to a variable twice in the same line.

grammar example
`part
  : Name=id
  | From=id COLON To=id // <-- offending line
;`

generated code
`
	case 2:
		p.EnterOuterAlt(localctx, 2)
		p.SetState(39)

		var _x = p.Id()

		localctx.(*PartContext).From = _x

		p.SetState(40)
		p.Match(RefParserCOLON)

		p.SetState(41)

		var _x = p.Id()

		localctx.(*PartContext).To = _x
`

**Comment by parrt** [comment]
probably time to move issues to antlr/antlr4?

**Comment by millergarym** [comment]
antlr/antlr4 doesn't currently compile
I've just submitted a pull request for this issue again the latest version of this repo that I could get to compile.

`[INFO] Reactor Summary:
[INFO] 
[INFO] ANTLR 4 ............................................ SUCCESS [  0.558 s]
[INFO] ANTLR 4 Runtime .................................... SUCCESS [  3.008 s]
[INFO] ANTLR 4 Tool ....................................... SUCCESS [  2.882 s]
[INFO] ANTLR 4 Maven plugin ............................... SUCCESS [  1.279 s]
[INFO] ANTLR 4 Runtime Test Annotations ................... SUCCESS [  0.020 s]
[INFO] ANTLR 4 Runtime Test Processors .................... SUCCESS [  0.045 s]
[INFO] ANTLR 4 Runtime Tests (2nd generation) ............. SUCCESS [  0.570 s]
[INFO] ANTLR 4 Tool Tests ................................. FAILURE [  4.590 s]
[INFO] ANTLR 4 Legacy Runtime Test Generator .............. SKIPPED
`

**Comment by parrt** [comment]
it compiles but doesn't pass all the tests; there are some C# tests that fail.

**Comment by millergarym** [comment]
Should install still work?

mvn -DskipTests install

**Comment by parrt** [comment]
yep. I just verified it. You might have to do it twice given mavens dependencies.

**Comment by parrt** [comment]
Note: all contributions must be accompanied by adding yourself to the contributors.txt file so we can keep the license clean. thanks!

**Comment by millergarym** [comment]
Submitted the pull request to antlr/antlr4

**Comment by pboyer** [comment]
@parrt Thanks for picking this up.
